"""add session time offsets

Revision ID: 5463b2470759
Revises: add_correlation_events
Create Date: 2026-02-03 19:19:34.895329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5463b2470759'
down_revision: Union[str, Sequence[str], None] = 'add_correlation_events'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_time_offsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('cpu_sync_timestamp_ns', sa.BigInteger(), nullable=False),
    sa.Column('gpu_sync_timestamp_ns', sa.BigInteger(), nullable=False),
    sa.Column('offset_ns', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_time_offsets_id'), 'session_time_offsets', ['id'], unique=False)
    op.drop_table('correlation_events')
    op.alter_column('cpu_samples', 'thread_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cpu_samples', 'stack_hash',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               nullable=True)
    op.create_index(op.f('ix_cpu_samples_id'), 'cpu_samples', ['id'], unique=False)
    op.alter_column('gpu_events', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.alter_column('stack_frames', 'hash',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('stack_frames', 'line_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stack_frames', sa.Column('line_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('stack_frames', 'hash',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.alter_column('gpu_events', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_cpu_samples_id'), table_name='cpu_samples')
    op.alter_column('cpu_samples', 'stack_hash',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('cpu_samples', 'thread_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('correlation_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('cpu_timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('cpu_stack_hash', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('gpu_kernel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('correlation_events_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('correlation_events_pkey'))
    )
    op.drop_index(op.f('ix_session_time_offsets_id'), table_name='session_time_offsets')
    op.drop_table('session_time_offsets')
    # ### end Alembic commands ###
